import fs from "node:fs";
import path from "node:path";
import ignore from "ignore";

export type FileKind = "ts" | "tsx" | "js" | "jsx" | "json" | "other";

export interface ScannedFile {
  path: string;
  relativePath: string;
  kind: FileKind;
  isGenerated: boolean;
}

export interface ScanResult {
  files: ScannedFile[];
  errors: Error[];
}

const ALWAYS_IGNORE = ["node_modules", ".git", "dist", ".tsgraph", ".gitignore"];

const GENERATED_PATTERNS = [
  /@generated/,
  /Code generated by/,
  /auto-generated/,
  /This file is generated/,
];

const FILE_EXT_MAP: Record<string, FileKind> = {
  ".ts": "ts",
  ".tsx": "tsx",
  ".js": "js",
  ".jsx": "jsx",
  ".json": "json",
};

function classifyFile(filePath: string): FileKind {
  return FILE_EXT_MAP[path.extname(filePath).toLowerCase()] ?? "other";
}

function checkGenerated(filePath: string): boolean {
  try {
    const fd = fs.openSync(filePath, "r");
    const buffer = Buffer.alloc(256);
    const bytesRead = fs.readSync(fd, buffer, 0, 256, 0);
    fs.closeSync(fd);
    const firstChunk = buffer.toString("utf-8", 0, bytesRead).split("\n")[0];
    return GENERATED_PATTERNS.some((p) => p.test(firstChunk));
  } catch {
    return false;
  }
}

export function scanFiles(rootDir: string): ScanResult {
  const ig = ignore().add(ALWAYS_IGNORE);
  const gitignorePath = path.join(rootDir, ".gitignore");
  try {
    ig.add(fs.readFileSync(gitignorePath, "utf-8"));
  } catch {
    // no .gitignore — built-in rules suffice
  }

  const files: ScannedFile[] = [];
  const errors: Error[] = [];

  function walk(dir: string) {
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch (err) {
      errors.push(err as Error);
      return;
    }

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      const relativePath = path.relative(rootDir, fullPath);

      if (entry.isDirectory()) {
        if (ig.ignores(relativePath + "/")) continue;
        walk(fullPath);
      } else if (entry.isFile()) {
        if (ig.ignores(relativePath)) continue;
        const kind = classifyFile(fullPath);
        files.push({
          path: fullPath,
          relativePath,
          kind,
          isGenerated: checkGenerated(fullPath),
        });
      }
    }
  }

  walk(rootDir);

  return { files, errors };
}
