import { describe, it, expect } from "vitest";
import path from "node:path";
import fs from "node:fs";
import os from "node:os";
import { scanFiles } from "./index.js";

function createTempDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), "tsgraph-test-"));
}

function writeFile(dir: string, relativePath: string, content: string) {
  const fullPath = path.join(dir, relativePath);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, content, "utf-8");
}

describe("scanFiles", () => {
  it("finds .ts files in a flat directory", () => {
    const dir = createTempDir();
    writeFile(dir, "index.ts", "");
    writeFile(dir, "util.ts", "");

    const result = scanFiles(dir);
    const paths = result.files.map((f) => f.relativePath).sort();
    expect(paths).toEqual(["index.ts", "util.ts"]);
    expect(result.errors).toEqual([]);

    fs.rmSync(dir, { recursive: true });
  });

  it("ignores node_modules by default", () => {
    const dir = createTempDir();
    writeFile(dir, "index.ts", "");
    writeFile(dir, "node_modules/foo/index.ts", "");
    writeFile(dir, "node_modules/bar/index.js", "");

    const result = scanFiles(dir);
    const paths = result.files.map((f) => f.relativePath);
    expect(paths).toEqual(["index.ts"]);
    fs.rmSync(dir, { recursive: true });
  });

  it("ignores .git, dist, .tsgraph by default", () => {
    const dir = createTempDir();
    writeFile(dir, "src/index.ts", "");
    writeFile(dir, ".git/HEAD", "");
    writeFile(dir, "dist/bundle.js", "");
    writeFile(dir, ".tsgraph/graph.json", "");

    const result = scanFiles(dir);
    const paths = result.files.map((f) => f.relativePath).sort();
    expect(paths).toEqual(["src/index.ts"]);
    fs.rmSync(dir, { recursive: true });
  });

  it("respects .gitignore patterns", () => {
    const dir = createTempDir();
    writeFile(dir, ".gitignore", "*.log\n/build");
    writeFile(dir, "src/index.ts", "");
    writeFile(dir, "server.log", "");
    writeFile(dir, "build/output.js", "");

    const result = scanFiles(dir);
    const paths = result.files.map((f) => f.relativePath);
    expect(paths).toEqual(["src/index.ts"]);
    fs.rmSync(dir, { recursive: true });
  });

  it("classifies file kinds correctly", () => {
    const dir = createTempDir();
    writeFile(dir, "a.ts", "");
    writeFile(dir, "b.tsx", "");
    writeFile(dir, "c.js", "");
    writeFile(dir, "d.jsx", "");
    writeFile(dir, "e.json", "");
    writeFile(dir, "f.css", "");

    const result = scanFiles(dir);
    const kinds = Object.fromEntries(
      result.files.map((f) => [f.relativePath, f.kind]),
    );
    expect(kinds["a.ts"]).toBe("ts");
    expect(kinds["b.tsx"]).toBe("tsx");
    expect(kinds["c.js"]).toBe("js");
    expect(kinds["d.jsx"]).toBe("jsx");
    expect(kinds["e.json"]).toBe("json");
    expect(kinds["f.css"]).toBe("other");
    fs.rmSync(dir, { recursive: true });
  });

  it("detects generated files by first-line comment", () => {
    const dir = createTempDir();
    writeFile(dir, "generated.ts", "// @generated\nconst x = 1;\n");
    writeFile(dir, "normal.ts", "const x = 1;\n");
    writeFile(dir, "auto.ts", "// auto-generated\nconst y = 2;\n");
    writeFile(dir, "codegen.ts", "// Code generated by protoc\nconst z = 3;\n");

    const result = scanFiles(dir);
    const genMap = Object.fromEntries(
      result.files.map((f) => [f.relativePath, f.isGenerated]),
    );
    expect(genMap["generated.ts"]).toBe(true);
    expect(genMap["normal.ts"]).toBe(false);
    expect(genMap["auto.ts"]).toBe(true);
    expect(genMap["codegen.ts"]).toBe(true);
    fs.rmSync(dir, { recursive: true });
  });

  it("handles missing .gitignore gracefully", () => {
    const dir = createTempDir();
    writeFile(dir, "index.ts", "");
    // Intentionally no .gitignore

    const result = scanFiles(dir);
    expect(result.files.length).toBe(1);
    expect(result.errors).toEqual([]);
    fs.rmSync(dir, { recursive: true });
  });

  it("walks nested directories", () => {
    const dir = createTempDir();
    writeFile(dir, "src/index.ts", "");
    writeFile(dir, "src/components/button.tsx", "");
    writeFile(dir, "src/utils/helpers.ts", "");

    const result = scanFiles(dir);
    const paths = result.files.map((f) => f.relativePath).sort();
    expect(paths).toEqual([
      "src/components/button.tsx",
      "src/index.ts",
      "src/utils/helpers.ts",
    ]);
    fs.rmSync(dir, { recursive: true });
  });
});
